"""empty message

Revision ID: 11b252ebcb47
Revises: 
Create Date: 2021-11-12 14:47:28.235325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b252ebcb47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('sub_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'page', 'sub_page', ['sub_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_column('page', 'sub_page_id')
    # ### end Alembic commands ###
