"""empty message

Revision ID: 19fc701019ae
Revises: c6a098604e73
Create Date: 2021-11-01 17:34:25.587460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fc701019ae'
down_revision = 'c6a098604e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('action_text', sa.String(length=25), nullable=True))
    op.add_column('services', sa.Column('colour', sa.String(length=80), nullable=True))
    op.add_column('services', sa.Column('url', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'url')
    op.drop_column('services', 'colour')
    op.drop_column('services', 'action_text')
    # ### end Alembic commands ###
