"""empty message

Revision ID: 1e0bf6537cce
Revises: e4c4c64ad3d7
Create Date: 2021-10-26 09:57:42.807647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0bf6537cce'
down_revision = 'e4c4c64ad3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_to_action', sa.Column('show_on_navbar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_to_action', 'show_on_navbar')
    # ### end Alembic commands ###
