"""empty message

Revision ID: 3567286c82e8
Revises: 5c51c4e11c9b
Create Date: 2021-10-30 12:16:17.515964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3567286c82e8'
down_revision = '5c51c4e11c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('process', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_table('process_title')
    # ### end Alembic commands ###
