"""empty message

Revision ID: 409b0edc8a32
Revises: 1e0bf6537cce
Create Date: 2021-10-27 09:55:41.711949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409b0edc8a32'
down_revision = '1e0bf6537cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_to_action', sa.Column('button_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_to_action', 'button_type')
    # ### end Alembic commands ###
