"""empty message

Revision ID: 4c14cc854aad
Revises: 77c559bf8bad
Create Date: 2021-10-27 18:20:40.112595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c14cc854aad'
down_revision = '77c559bf8bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('headlines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headlines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='headlines_pkey')
    )
    op.drop_table('headline')
    # ### end Alembic commands ###
