"""empty message

Revision ID: 50e996280544
Revises: d1c5d5b71ebe
Create Date: 2021-10-22 08:15:34.603620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e996280544'
down_revision = 'd1c5d5b71ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_allowed', sa.Boolean(), nullable=True))
    op.add_column('api_keys', sa.Column('user_input', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'user_input')
    op.drop_column('api_keys', 'is_allowed')
    # ### end Alembic commands ###
