"""empty message

Revision ID: 77c559bf8bad
Revises: 409b0edc8a32
Create Date: 2021-10-27 17:45:55.797381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c559bf8bad'
down_revision = '409b0edc8a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('headlines')
    # ### end Alembic commands ###
