"""empty message

Revision ID: 9bd54a0d9e7d
Revises: 50e996280544
Create Date: 2021-10-22 12:10:51.927009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd54a0d9e7d'
down_revision = '50e996280544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.String(length=500), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('api_keys', 'is_allowed')
    op.drop_column('api_keys', 'user_input')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('user_input', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('is_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('api_access')
    # ### end Alembic commands ###
