"""empty message

Revision ID: a171bc2ada60
Revises: fda1e66a88ad
Create Date: 2021-11-01 12:49:49.813416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a171bc2ada60'
down_revision = 'fda1e66a88ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pricing', sa.Column('button_text', sa.String(length=80), nullable=True))
    op.add_column('pricing', sa.Column('button_type', sa.String(length=80), nullable=True))
    op.add_column('pricing', sa.Column('button_url', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing', 'button_url')
    op.drop_column('pricing', 'button_type')
    op.drop_column('pricing', 'button_text')
    op.drop_table('testimonial_title')
    # ### end Alembic commands ###
