"""empty message

Revision ID: be3a285b384d
Revises: f34192105cfb
Create Date: 2021-10-31 17:18:01.898924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3a285b384d'
down_revision = 'f34192105cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_attribute', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_attribute', 'is_available')
    # ### end Alembic commands ###
