"""empty message

Revision ID: e4c4c64ad3d7
Revises: 9bd54a0d9e7d
Create Date: 2021-10-22 14:17:51.511967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c4c64ad3d7'
down_revision = '9bd54a0d9e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_access', sa.Column('session_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_access', 'session_id')
    # ### end Alembic commands ###
