"""empty message

Revision ID: fda1e66a88ad
Revises: 43a22d0a19b3
Create Date: 2021-11-01 10:59:20.159611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda1e66a88ad'
down_revision = '43a22d0a19b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('is_popular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing', 'is_popular')
    # ### end Alembic commands ###
